importing numpy,pandas,linearregression model


In [23]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

data is in form of y=2x1+3x2+4x3+5

In [24]:
data=pd.read_csv('data.csv')

In [25]:
data

x1  x2  x3    y
0 -94  24  22  -23
1  12  63  11  262
2  27  87  23  412
3  56   9   6  168
4  66  12  76  477
5  78   1  53  376
6  25  23  91  488
7  98  43   2  338
8  45  32   0  191
9  21  11   2   88

In [26]:
x=data[['x1','x2','x3']].values

In [27]:
x

array([[-94,  24,  22],
       [ 12,  63,  11],
       [ 27,  87,  23],
       [ 56,   9,   6],
       [ 66,  12,  76],
       [ 78,   1,  53],
       [ 25,  23,  91],
       [ 98,  43,   2],
       [ 45,  32,   0],
       [ 21,  11,   2]])

In [28]:
y=data[['y']].values
y

array([[-23],
       [262],
       [412],
       [168],
       [477],
       [376],
       [488],
       [338],
       [191],
       [ 88]])

In [29]:
model=LinearRegression()

In [30]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

the intercept of the equation is 5

In [31]:
model.intercept_

array([5.])

the coefficients of x1=2,x2=3,x3=4

In [32]:
model.coef_

array([[2., 3., 4.]])

In [33]:
y_predict=model.predict(x)

In [34]:
y_predict

array([[-23.],
       [262.],
       [412.],
       [168.],
       [477.],
       [376.],
       [488.],
       [338.],
       [191.],
       [ 88.]])

if x1=3,x2=2,x3=1 then y should be 21 according to the equation y=2x1+3x2+4x3+5

In [37]:
x_new=np.array([[3,  2,  1]])

In [38]:
y_new=model.predict(x_new)

In [39]:
y_new

array([[21.]])